# Generated by Django 3.2.7 on 2021-10-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name of Hotel')),
                ('city', models.CharField(max_length=45, verbose_name='City of Hotel')),
                ('address', models.CharField(max_length=45, verbose_name='Address of Hotel')),
                ('stars', models.IntegerField(choices=[(1, 'Una estrella'), (2, 'Dos estrellas'), (3, 'Tres estrellas'), (4, 'Cuatro estrellas'), (5, 'Cinco estrellas')], verbose_name='Stars of Hotel')),
            ],
        ),
    ]
