# Generated by Django 3.1.1 on 2021-10-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20211006_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='picture',
            field=models.CharField(default='https://media-cdn.tripadvisor.com/media/photo-s/16/1a/ea/54/hotel-presidente-4s.jpg', max_length=250, verbose_name='Hotel picture'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='begining_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ending_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
